[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["allisonthuang <<>>"]
description = ""
name = "allisonthuanggithubio"
version = "0.1.0"
[tool.poetry.dependencies]
poetry = "^1.1"
python = "^3.8"
[tool.poetry.dev-dependencies]
